---
# tasks file for roles/pre
- name: get azure subscription info
  azure.azcollection.azure_rm_subscription_info:
    all: True
  register: azure_subscription

- set_fact:
    azure_subscription_id: "{{ azure_subscription.subscriptions[0].subscription_id }}"
- set_fact:
    azure_tenant_id: "{{ azure_subscription.subscriptions[0].tenant_id }}"
