- include_tasks: info.yml

- name: check for existing ad app
  azure.azcollection.azure_rm_adapplication_info:
    tenant: "{{ _azr_tenant_id }}"
  register: _ad_applications
  no_log: true

- set_fact:
    _ad_application: "{{ _ad_applications | json_query(jmesquery) }}"
  vars:
    jmesquery: "applications[?app_display_name == `{{ app_display_name }}`]"

- block:
    - name: destroy ad sp
      azure.azcollection.azure_rm_adserviceprincipal:
        tenant: "{{ _azr_tenant_id }}"
        app_id: "{{ _ad_application[0].app_id }}"
        state: absent

    - name: destroy ad application
      azure.azcollection.azure_rm_adapplication:
        tenant: "{{ _azr_tenant_id }}"
        app_id: "{{ _ad_application[0].app_id }}"
        state: absent
  when: _ad_application | length > 0
